- title: intro
  children:
  - application-rationalization
  - evaluate-modernization
  - choose-your-approach
- title: from-monolith-to-microservices
  children:
  - the-microwizard
  - microservices-in-action
  - architectural-details
- title: whats-next
- title: new-content
  children:
  - not-written-yet
  - not-written-yet
  - not-written-yet
- title: new-content
  children:
  - not-written-yet
  - not-written-yet
  - not-written-yet
